import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p> I'm the root layout</p>
        <Image
          src={"/formation-next-js.png"}
          alt="Logo"
          width={100}
          height={70}
        />
        {children}
      </body>
    </html>
  );
}
